services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - starter-network

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '8080:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - starter-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  starter-network:
    name: starter-network
    driver: bridge
